# Version du docker compose utilisé
version: '3.1'

services:
  #Service php
  php:
    #Construire l'image php
    build:
      #Path relatif du fichier Dockerfile
      context: .
      #Nom du dockerfile ( Dockerfile )
      dockerfile: Dockerfile
    #Port du conteneur
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
